### ISSUE TITLE
spec tests are broken

### ISSUE THREAD

**Issue by thistonyb** [learn-co-curriculum/dynamic-orm-lab#21]
The following spec tests have extra data, it looks like another copy of the data where the keys are indices of the array...its pretty weird. But I am pretty sure they do not belong. Specifically the save, find_by, and find_by_name have this included in their hash in the test: #, 0=>1, 1=>"Susan", 2=>10

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙

**Comment by junymc** [comment]
I still have the same issue. It looks like the problem was not solved. Please check again.
